# Generated by Django 5.0.6 on 2024-06-17 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_description_alter_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_description',
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
