# Generated by Django 5.0.6 on 2024-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', models.IntegerField()),
                ('pub_name', models.CharField(max_length=255)),
                ('sub_id', models.IntegerField()),
                ('sub_name', models.CharField(max_length=255)),
                ('sub_time', models.DateTimeField()),
            ],
        ),
    ]
